name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Frontend setup and build
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          keep_files: false
          permissions:
            pages: write

      # Backend build
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Set up Go environment
        run: |
          echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          echo "export GOOS=linux" >> $GITHUB_ENV
          echo "export GOARCH=amd64" >> $GITHUB_ENV
          echo "export CGO_ENABLED=0" >> $GITHUB_ENV

      - name: Build backend
        working-directory: ./backend
        run: |
          go mod tidy
          go build -o submission ./cmd/main.go

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-build
          path: ./backend/submission