name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Frontend build steps
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/dist
          if-no-files-found: error

      # Backend/Go steps
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Set up Go environment
        run: |
          echo "Setting up Go environment"
          echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          echo "export GOOS=linux" >> $GITHUB_ENV
          echo "export GOARCH=amd64" >> $GITHUB_ENV
          echo "export CGO_ENABLED=0" >> $GITHUB_ENV

      - name: Verify Go installation
        run: |
          go version
          go env

      - name: Install backend dependencies
        run: |
          cd backend
          go mod tidy

      - name: Build backend
        run: |
          cd backend
          go build -o submission ./cmd/main.go

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-build
          path: ./backend/submission